trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  workingDirectory: terraform

steps:

# 1. Descargar código
- checkout: self

# 2. Instalar Terraform
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

# 3. Init
- task: AzureCLI@2
  inputs:
    azureSubscription: 'AzureServiceConnection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      cd $(workingDirectory)
      terraform init

# 4. Plan
- task: AzureCLI@2
  inputs:
    azureSubscription: 'AzureServiceConnection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      cd $(workingDirectory)
      terraform plan -out=tfplan

# 5. Apply (opcional en entrega)
- task: AzureCLI@2
  inputs:
    azureSubscription: 'AzureServiceConnection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      cd $(workingDirectory)
      terraform apply -auto-approve tfplan